name: Build and Jekyll site and run htmlproofer

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Fetch main
        run: |
          git fetch origin main --depth 1
          git branch

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - name: Use cache to shorten build time
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build Jekyll site
        uses: helaili/jekyll-action@v2
        with:
          build_only: true
          build_dir: _site

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
      - name: Install gems
        run: |
          gem install html-proofer
          gem install typhoeus

      - name: Cache HTMLProofer
        id: cache-htmlproofer
        uses: actions/cache@v4

      - name: Check HTML using htmlproofer
        uses: chabad360/htmlproofer@v2
        with:
          path: tmp/.htmlproofer
          key: ${{ runner.os }}-htmlproofer

      - name: Run htmlproofer
        run: |
          ruby scripts/htmlproofer.rb
          ls

      - name: Error log
        run: cat html_proofer_errors.txt
