name: Build and Jekyll site and run htmlproofer

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - name: Use cache to shorten build time
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build Jekyll site
        uses: helaili/jekyll-action@v2
        with:
          build_only: true
          build_dir: _site

      - name: all dirs
        run: |
          ls
          pwd

      - name: Check HTML using htmlproofer
        uses: chabad360/htmlproofer@master
        with:
          directory: "_site"
          arguments: |
            --ignore-urls "https://fonts.googleapis.com,https://fonts.gstatic.com,_site/_posts/README/index.html"
            --ignore-files "/.+\/_posts\/README.md"
            --ignore-status-codes "0,403, 429, 503, 999"
