name: Link check (weekly)

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "10 02 * * 6"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Jekyll site
        uses: helaili/jekyll-action@v2
        with:
          build_only: true
          build_dir: _site

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --no-progress _site/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
