name: Update Contributors

on:
  pull_request:
  push:
    branches:
      - mai
jobs:
  run-meta:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python -m pip install --upgrade pip wheel
          echo "$PWD"
          git branch
      - name: Install pyosmeta and run update contribs
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          pip install pyosmeta@git+https://github.com/pyopensci/update-web-metadata
          echo "$PWD"
          # Skip error for when this pr actually works
          # python -bb -W error scripts/parse-contributors.py
          python scripts/parse-contributors.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: _data/contributors.yml
          author: Leah <leah@pyopensci.org>
          base: main
          branch: contribs
          commit-message: "Update: Contributor file update"
          delete-branch: true
          title: Update new contributors
        env:
          # Token needed to provide permissions to bot to push to branch
          # https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-536204092
          GITHUB_TOKEN: ${{ secrets.PYOS_PR_TOKEN }}
